blank_issues_enabled: true
contact_links:
  - name: Pepe Server
    url: https://discord.gg/pepe
    about: Please use this Discord Server to ask questions and get support. We don't answer questions here and they will likely be closed and redirected to the Discord server.
