name: Build and Lint

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16

      - name: Install dependencies
        run: yarn --immutable

      - name: Build website
        run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16

      - name: Install dependencies
        run: yarn --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn prettier:check
